# Generated by Django 2.0.7 on 2018-11-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20181105_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='score',
            field=models.SmallIntegerField(default=1),
        ),
    ]
