# Generated by Django 2.0.7 on 2018-11-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_book_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.AddField(
            model_name='author',
            name='author_summary',
            field=models.TextField(default='null', help_text='Enter a brief description of the author', max_length=1000),
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='haha', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='score',
            field=models.SmallIntegerField(),
        ),
    ]
