# Generated by Django 2.0.7 on 2018-11-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20181108_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name', 'author_summary']},
        ),
    ]
